### PR TITLE
feat: add dependabot config

### LINKED ISSUE #210: Try to add Github dependabot

### PR DESCRIPTION
**Pull request by od-hunter**
resolves #210

### CODE REVIEW

**Comment by od-hunter** [comment]
Hello @GrapeBaBa, kindly review please

**Comment by GrapeBaBa** [comment]
> Hello @GrapeBaBa, kindly review please

Thanks, sorry for late

**Comment by od-hunter** [comment]
Hi @GrapeBaBa , sorry for asking just curious, please will there be any form of remuneration for my merged pr’s?

**Comment by GrapeBaBa** [comment]
grapebaba



发自我的iPhone


------------------ Original ------------------
From: Hunter001 ***@***.***&gt;
Date: Tue,Oct 22,2024 8:44 PM
To: optimism-java/hildr ***@***.***&gt;
Cc: Chen Kai ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [optimism-java/hildr] feat: add dependabot config (PR #223)





 
Hi @GrapeBaBa , sorry for asking just curious, please will there be any form of renumeration for my merged pr’s?

**Comment by od-hunter** [comment]
> grapebaba 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Hunter001 ***@***.***&gt; Date: Tue,Oct 22,2024 8:44 PM To: optimism-java/hildr ***@***.***&gt; Cc: Chen Kai ***@***.***&gt;, Mention ***@***.***&gt; Subject: Re: [optimism-java/hildr] feat: add dependabot config (PR #223) Hi @GrapeBaBa , sorry for asking just curious, please will there be any form of renumeration for my merged pr’s? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Pardon?

**Pull request merged**
